import { StyleSheet } from "react-native"

export default globalStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9F8',
        paddingHorizontal: 20,
    },
    centeredContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#F8F9F8',
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#1B4332',
        marginBottom: 10,
    },
    subtitle: {
        fontSize: 18,
        color: '#40916C',
        marginBottom: 20,
    },
    formLabels : {
        fontSize : 14,
        fontWeight: '600',
        color: '#1B4332',
        marginBottom: 4,
    },
    formField : {
        width : "100%",
        marginVertical : 10,
    },
    textInput : {
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
    },
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginVertical: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    glassCard: {
        backgroundColor: 'rgba(255, 255, 255, 0.85)',
        borderRadius: 20,
        padding: 16,
        marginVertical: 10,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.5)',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
    },
    heroSection: {
        backgroundColor: '#1B4332',
        padding: 24,
        paddingTop: 30,
        paddingBottom: 40,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
    },
    heroTitle: {
        fontSize: 32,
        fontWeight: '900',
        color: '#FFFFFF',
        letterSpacing: -0.5,
    },
    heroSubtitle: {
        fontSize: 16,
        color: '#D8F3DC',
        marginTop: 4,
        opacity: 0.9,
    },
    statCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        width: 140,
        marginRight: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    statLabel: {
        fontSize: 12,
        color: '#666',
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 4,
    },
    statValue: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1B4332',
    },
    statCardTeal: {
        backgroundColor: '#E6FFFA',
        borderColor: '#38B2AC',
    },
    statCardBlue: {
        backgroundColor: '#EBF8FF',
        borderColor: '#4299E1',
    },
    statCardAmber: {
        backgroundColor: '#FFFBEB',
        borderColor: '#F6E05E',
    },
    vibrantFAB: {
        backgroundColor: '#FF9F1C',
    }
})