# Generated by Django 4.2.30 on 2026-04-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fci_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_register',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
