# Generated by Django 4.2.29 on 2026-09-19 05:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Fci_App', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop_register',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='crop_register',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crop_register',
            name='grade',
            field=models.CharField(choices=[('A', 'Grade A (FAQ Premium +5%)'), ('B', 'Grade B (Standard FAQ)'), ('C', 'Grade C (Below Standard -10%)')], default='B', max_length=10),
        ),
        migrations.AddField(
            model_name='crop_register',
            name='moisture_pct',
            field=models.FloatField(default=12.0, help_text='Harvest moisture percentage (standard 12-14%)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='msp',
            field=models.IntegerField(help_text='Government Minimum Support Price in INR per kg'),
        ),
        migrations.AlterField(
            model_name='crop_register',
            name='farmer_city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='crop_register',
            name='name',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='crop_register',
            name='quantity',
            field=models.IntegerField(help_text='Quantity in kg'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='crop_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Fci_App.crop_register'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.IntegerField(help_text='Agreed/Offered price per kg in INR'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deal_done', 'Deal Done'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('inspected', 'Inspected'), ('payment_done', 'Payment Done'), ('rejected', 'Rejected'), ('waiting_for_farmer', 'Waiting for Farmer')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['name'], name='Fci_App_cro_name_325452_idx'),
        ),
        migrations.AddIndex(
            model_name='crop_register',
            index=models.Index(fields=['farmer_city', 'dealer_type'], name='Fci_App_cro_farmer__fab269_idx'),
        ),
        migrations.AddIndex(
            model_name='crop_register',
            index=models.Index(fields=['name'], name='Fci_App_cro_name_ee3f95_idx'),
        ),
        migrations.AddIndex(
            model_name='crop_register',
            index=models.Index(fields=['farmer'], name='Fci_App_cro_farmer__d1ac01_idx'),
        ),
        migrations.AddIndex(
            model_name='crop_register',
            index=models.Index(fields=['created_at'], name='Fci_App_cro_created_2fbccf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['farmer', 'status'], name='Fci_App_tra_farmer__c61131_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['dealer', 'status'], name='Fci_App_tra_dealer__603138_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='Fci_App_tra_status_306676_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='Fci_App_tra_created_524b70_idx'),
        ),
    ]
